# coding: utf-8

"""
    QEDIT - Asset Transfers

    This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/).   # noqa: E501

    OpenAPI spec version: 1.6.2
    Contact: dev@qed-it.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pyqedit
from pyqedit.models.get_tasks_request import GetTasksRequest  # noqa: E501
from pyqedit.rest import ApiException


class TestGetTasksRequest(unittest.TestCase):
    """GetTasksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTasksRequest(self):
        """Test GetTasksRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyqedit.models.get_tasks_request.GetTasksRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
