/**
 * QEDIT - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.5.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QedItAssetTransfers);
  }
}(this, function(expect, QedItAssetTransfers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QedItAssetTransfers.GetSyncStatusResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetSyncStatusResponse', function() {
    it('should create an instance of GetSyncStatusResponse', function() {
      // uncomment below and update the code to test GetSyncStatusResponse
      //var instance = new QedItAssetTransfers.GetSyncStatusResponse();
      //expect(instance).to.be.a(QedItAssetTransfers.GetSyncStatusResponse);
    });

    it('should have the property inSync (base name: "in_sync")', function() {
      // uncomment below and update the code to test the property inSync
      //var instance = new QedItAssetTransfers.GetSyncStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property blockchainBlockHeight (base name: "blockchain_block_height")', function() {
      // uncomment below and update the code to test the property blockchainBlockHeight
      //var instance = new QedItAssetTransfers.GetSyncStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastProcessedBlockHeight (base name: "last_processed_block_height")', function() {
      // uncomment below and update the code to test the property lastProcessedBlockHeight
      //var instance = new QedItAssetTransfers.GetSyncStatusResponse();
      //expect(instance).to.be();
    });

  });

}));
