/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnalyticsRule'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnalyticsRule'));
  } else {
    // Browser globals (root is window)
    if (!root.QedItAssetTransfers) {
      root.QedItAssetTransfers = {};
    }
    root.QedItAssetTransfers.AnalyticsConfidentialIssuanceDescription = factory(root.QedItAssetTransfers.ApiClient, root.QedItAssetTransfers.AnalyticsRule);
  }
}(this, function(ApiClient, AnalyticsRule) {
  'use strict';



  /**
   * The AnalyticsConfidentialIssuanceDescription model module.
   * @module model/AnalyticsConfidentialIssuanceDescription
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>AnalyticsConfidentialIssuanceDescription</code>.
   * @alias module:model/AnalyticsConfidentialIssuanceDescription
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>AnalyticsConfidentialIssuanceDescription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalyticsConfidentialIssuanceDescription} obj Optional instance to populate.
   * @return {module:model/AnalyticsConfidentialIssuanceDescription} The populated <code>AnalyticsConfidentialIssuanceDescription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('input_cv')) {
        obj['input_cv'] = ApiClient.convertToType(data['input_cv'], 'String');
      }
      if (data.hasOwnProperty('zkproof')) {
        obj['zkproof'] = ApiClient.convertToType(data['zkproof'], 'String');
      }
      if (data.hasOwnProperty('rule')) {
        obj['rule'] = AnalyticsRule.constructFromObject(data['rule']);
      }
    }
    return obj;
  }

  /**
   * @member {String} input_cv
   */
  exports.prototype['input_cv'] = undefined;
  /**
   * @member {String} zkproof
   */
  exports.prototype['zkproof'] = undefined;
  /**
   * @member {module:model/AnalyticsRule} rule
   */
  exports.prototype['rule'] = undefined;



  return exports;
}));


