/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Rule from './Rule';

/**
 * The DeleteRuleRequest model module.
 * @module model/DeleteRuleRequest
 * @version 1.0.0
 */
class DeleteRuleRequest {
    /**
     * Constructs a new <code>DeleteRuleRequest</code>.
     * @alias module:model/DeleteRuleRequest
     * @param walletLabel {String} 
     * @param authorization {String} 
     * @param rulesToDelete {Array.<module:model/Rule>} 
     */
    constructor(walletLabel, authorization, rulesToDelete) { 
        
        DeleteRuleRequest.initialize(this, walletLabel, authorization, rulesToDelete);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, walletLabel, authorization, rulesToDelete) { 
        obj['wallet_label'] = walletLabel;
        obj['authorization'] = authorization;
        obj['rules_to_delete'] = rulesToDelete;
    }

    /**
     * Constructs a <code>DeleteRuleRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteRuleRequest} obj Optional instance to populate.
     * @return {module:model/DeleteRuleRequest} The populated <code>DeleteRuleRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteRuleRequest();

            if (data.hasOwnProperty('wallet_label')) {
                obj['wallet_label'] = ApiClient.convertToType(data['wallet_label'], 'String');
            }
            if (data.hasOwnProperty('authorization')) {
                obj['authorization'] = ApiClient.convertToType(data['authorization'], 'String');
            }
            if (data.hasOwnProperty('rules_to_delete')) {
                obj['rules_to_delete'] = ApiClient.convertToType(data['rules_to_delete'], [Rule]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} wallet_label
 */
DeleteRuleRequest.prototype['wallet_label'] = undefined;

/**
 * @member {String} authorization
 */
DeleteRuleRequest.prototype['authorization'] = undefined;

/**
 * @member {Array.<module:model/Rule>} rules_to_delete
 */
DeleteRuleRequest.prototype['rules_to_delete'] = undefined;






export default DeleteRuleRequest;

