/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenerateWalletRequest model module.
 * @module model/GenerateWalletRequest
 * @version 1.0.0
 */
class GenerateWalletRequest {
    /**
     * Constructs a new <code>GenerateWalletRequest</code>.
     * @alias module:model/GenerateWalletRequest
     * @param walletLabel {String} 
     * @param authorization {String} 
     */
    constructor(walletLabel, authorization) { 
        
        GenerateWalletRequest.initialize(this, walletLabel, authorization);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, walletLabel, authorization) { 
        obj['wallet_label'] = walletLabel;
        obj['authorization'] = authorization;
    }

    /**
     * Constructs a <code>GenerateWalletRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateWalletRequest} obj Optional instance to populate.
     * @return {module:model/GenerateWalletRequest} The populated <code>GenerateWalletRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateWalletRequest();

            if (data.hasOwnProperty('wallet_label')) {
                obj['wallet_label'] = ApiClient.convertToType(data['wallet_label'], 'String');
            }
            if (data.hasOwnProperty('authorization')) {
                obj['authorization'] = ApiClient.convertToType(data['authorization'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} wallet_label
 */
GenerateWalletRequest.prototype['wallet_label'] = undefined;

/**
 * @member {String} authorization
 */
GenerateWalletRequest.prototype['authorization'] = undefined;






export default GenerateWalletRequest;

