/**
 * QEDIT - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.5.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QedItAssetTransfers) {
      root.QedItAssetTransfers = {};
    }
    root.QedItAssetTransfers.GetAllWalletsResponse = factory(root.QedItAssetTransfers.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The GetAllWalletsResponse model module.
   * @module model/GetAllWalletsResponse
   * @version 1.5.0
   */

  /**
   * Constructs a new <code>GetAllWalletsResponse</code>.
   * @alias module:model/GetAllWalletsResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>GetAllWalletsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAllWalletsResponse} obj Optional instance to populate.
   * @return {module:model/GetAllWalletsResponse} The populated <code>GetAllWalletsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('wallet_ids')) {
        obj['wallet_ids'] = ApiClient.convertToType(data['wallet_ids'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The IDs of the Wallets currently active in this Node
   * @member {Array.<String>} wallet_ids
   */
  exports.prototype['wallet_ids'] = undefined;



  return exports;
}));


