/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.2.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QedItAssetTransfers) {
      root.QedItAssetTransfers = {};
    }
    root.QedItAssetTransfers.ImportWalletRequest = factory(root.QedItAssetTransfers.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ImportWalletRequest model module.
   * @module model/ImportWalletRequest
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>ImportWalletRequest</code>.
   * @alias module:model/ImportWalletRequest
   * @class
   * @param walletId {String} 
   * @param encryptedSk {String} 
   * @param authorization {String} 
   * @param salt {String} 
   */
  var exports = function(walletId, encryptedSk, authorization, salt) {
    var _this = this;

    _this['wallet_id'] = walletId;
    _this['encrypted_sk'] = encryptedSk;
    _this['authorization'] = authorization;
    _this['salt'] = salt;
  };

  /**
   * Constructs a <code>ImportWalletRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImportWalletRequest} obj Optional instance to populate.
   * @return {module:model/ImportWalletRequest} The populated <code>ImportWalletRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('wallet_id')) {
        obj['wallet_id'] = ApiClient.convertToType(data['wallet_id'], 'String');
      }
      if (data.hasOwnProperty('encrypted_sk')) {
        obj['encrypted_sk'] = ApiClient.convertToType(data['encrypted_sk'], 'String');
      }
      if (data.hasOwnProperty('authorization')) {
        obj['authorization'] = ApiClient.convertToType(data['authorization'], 'String');
      }
      if (data.hasOwnProperty('salt')) {
        obj['salt'] = ApiClient.convertToType(data['salt'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} wallet_id
   */
  exports.prototype['wallet_id'] = undefined;
  /**
   * @member {String} encrypted_sk
   */
  exports.prototype['encrypted_sk'] = undefined;
  /**
   * @member {String} authorization
   */
  exports.prototype['authorization'] = undefined;
  /**
   * @member {String} salt
   */
  exports.prototype['salt'] = undefined;



  return exports;
}));


