/**
 * QEDIT – Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.2.3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnalyticsOutput', 'model/AnalyticsOutputDescription', 'model/AnalyticsPublicIssuanceDescription'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnalyticsOutput'), require('./AnalyticsOutputDescription'), require('./AnalyticsPublicIssuanceDescription'));
  } else {
    // Browser globals (root is window)
    if (!root.QedItAssetTransfers) {
      root.QedItAssetTransfers = {};
    }
    root.QedItAssetTransfers.PublicAnalyticsOutput = factory(root.QedItAssetTransfers.ApiClient, root.QedItAssetTransfers.AnalyticsOutput, root.QedItAssetTransfers.AnalyticsOutputDescription, root.QedItAssetTransfers.AnalyticsPublicIssuanceDescription);
  }
}(this, function(ApiClient, AnalyticsOutput, AnalyticsOutputDescription, AnalyticsPublicIssuanceDescription) {
  'use strict';



  /**
   * The PublicAnalyticsOutput model module.
   * @module model/PublicAnalyticsOutput
   * @version 1.2.3
   */

  /**
   * Constructs a new <code>PublicAnalyticsOutput</code>.
   * @alias module:model/PublicAnalyticsOutput
   * @class
   * @extends module:model/AnalyticsOutput
   * @implements module:model/AnalyticsOutput
   * @param isConfidential {} 
   * @param outputDescription {} 
   * @param publicIssuanceDescription {} 
   */
  var exports = function(isConfidential, outputDescription, publicIssuanceDescription) {
    var _this = this;

    AnalyticsOutput.call(_this, isConfidential, outputDescription);
    _this['public_issuance_description'] = publicIssuanceDescription;
  };

  /**
   * Constructs a <code>PublicAnalyticsOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicAnalyticsOutput} obj Optional instance to populate.
   * @return {module:model/PublicAnalyticsOutput} The populated <code>PublicAnalyticsOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      AnalyticsOutput.constructFromObject(data, obj);
      if (data.hasOwnProperty('public_issuance_description')) {
        obj['public_issuance_description'] = AnalyticsPublicIssuanceDescription.constructFromObject(data['public_issuance_description']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(AnalyticsOutput.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/AnalyticsPublicIssuanceDescription} public_issuance_description
   */
  exports.prototype['public_issuance_description'] = undefined;

  // Implement AnalyticsOutput interface:
  /**
   * @member {Boolean} is_confidential
   */
exports.prototype['is_confidential'] = undefined;

  /**
   * @member {module:model/AnalyticsOutputDescription} output_description
   */
exports.prototype['output_description'] = undefined;



  return exports;
}));


