/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse', 'model/GetBlocksRequest', 'model/GetBlocksResponse', 'model/GetTransactionsRequest', 'model/GetTransactionsResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/GetBlocksRequest'), require('../model/GetBlocksResponse'), require('../model/GetTransactionsRequest'), require('../model/GetTransactionsResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.QedItAssetTransfers) {
      root.QedItAssetTransfers = {};
    }
    root.QedItAssetTransfers.AnalyticsApi = factory(root.QedItAssetTransfers.ApiClient, root.QedItAssetTransfers.ErrorResponse, root.QedItAssetTransfers.GetBlocksRequest, root.QedItAssetTransfers.GetBlocksResponse, root.QedItAssetTransfers.GetTransactionsRequest, root.QedItAssetTransfers.GetTransactionsResponse);
  }
}(this, function(ApiClient, ErrorResponse, GetBlocksRequest, GetBlocksResponse, GetTransactionsRequest, GetTransactionsResponse) {
  'use strict';

  /**
   * Analytics service.
   * @module api/AnalyticsApi
   * @version 1.1.0
   */

  /**
   * Constructs a new AnalyticsApi. 
   * @alias module:api/AnalyticsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get details on past blocks
     * @param {module:model/GetBlocksRequest} getBlocksRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetBlocksResponse} and HTTP response
     */
    this.analyticsGetBlocksPostWithHttpInfo = function(getBlocksRequest) {
      var postBody = getBlocksRequest;

      // verify the required parameter 'getBlocksRequest' is set
      if (getBlocksRequest === undefined || getBlocksRequest === null) {
        throw new Error("Missing the required parameter 'getBlocksRequest' when calling analyticsGetBlocksPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetBlocksResponse;

      return this.apiClient.callApi(
        '/analytics/get_blocks', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get details on past blocks
     * @param {module:model/GetBlocksRequest} getBlocksRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetBlocksResponse}
     */
    this.analyticsGetBlocksPost = function(getBlocksRequest) {
      return this.analyticsGetBlocksPostWithHttpInfo(getBlocksRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get details on past transactions
     * @param {module:model/GetTransactionsRequest} getTransactionsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetTransactionsResponse} and HTTP response
     */
    this.analyticsGetTransactionsPostWithHttpInfo = function(getTransactionsRequest) {
      var postBody = getTransactionsRequest;

      // verify the required parameter 'getTransactionsRequest' is set
      if (getTransactionsRequest === undefined || getTransactionsRequest === null) {
        throw new Error("Missing the required parameter 'getTransactionsRequest' when calling analyticsGetTransactionsPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetTransactionsResponse;

      return this.apiClient.callApi(
        '/analytics/get_transactions', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get details on past transactions
     * @param {module:model/GetTransactionsRequest} getTransactionsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetTransactionsResponse}
     */
    this.analyticsGetTransactionsPost = function(getTransactionsRequest) {
      return this.analyticsGetTransactionsPostWithHttpInfo(getTransactionsRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
