/**
 * QED-it - Asset Transfers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BalanceForAsset from './model/BalanceForAsset';
import Block from './model/Block';
import CreateRuleRequest from './model/CreateRuleRequest';
import DeleteRuleRequest from './model/DeleteRuleRequest';
import DeleteWalletRequest from './model/DeleteWalletRequest';
import ExportWalletRequest from './model/ExportWalletRequest';
import ExportWalletResponse from './model/ExportWalletResponse';
import GenerateWalletRequest from './model/GenerateWalletRequest';
import GetAllWalletsResponse from './model/GetAllWalletsResponse';
import GetBlocksRequest from './model/GetBlocksRequest';
import GetBlocksResponse from './model/GetBlocksResponse';
import GetNewAddressRequest from './model/GetNewAddressRequest';
import GetNewAddressResponse from './model/GetNewAddressResponse';
import GetPublicKeyRequest from './model/GetPublicKeyRequest';
import GetPublicKeyResponse from './model/GetPublicKeyResponse';
import GetRulesResponse from './model/GetRulesResponse';
import GetTransactionsRequest from './model/GetTransactionsRequest';
import GetTransactionsResponse from './model/GetTransactionsResponse';
import GetWalletBalanceRequest from './model/GetWalletBalanceRequest';
import GetWalletBalanceResponse from './model/GetWalletBalanceResponse';
import ImportWalletRequest from './model/ImportWalletRequest';
import IssueAssetRequest from './model/IssueAssetRequest';
import Rule from './model/Rule';
import TransactionsForWallet from './model/TransactionsForWallet';
import TransferAssetRequest from './model/TransferAssetRequest';
import TransferAssetRequestRecipientAddress from './model/TransferAssetRequestRecipientAddress';
import UnlockWalletRequest from './model/UnlockWalletRequest';
import AnalyticsApi from './api/AnalyticsApi';
import NodeApi from './api/NodeApi';
import WalletApi from './api/WalletApi';


/**
* ERROR_UNKNOWN.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var QedItAssetTransfers = require('index'); // See note below*.
* var xxxSvc = new QedItAssetTransfers.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new QedItAssetTransfers.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new QedItAssetTransfers.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new QedItAssetTransfers.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BalanceForAsset model constructor.
     * @property {module:model/BalanceForAsset}
     */
    BalanceForAsset,

    /**
     * The Block model constructor.
     * @property {module:model/Block}
     */
    Block,

    /**
     * The CreateRuleRequest model constructor.
     * @property {module:model/CreateRuleRequest}
     */
    CreateRuleRequest,

    /**
     * The DeleteRuleRequest model constructor.
     * @property {module:model/DeleteRuleRequest}
     */
    DeleteRuleRequest,

    /**
     * The DeleteWalletRequest model constructor.
     * @property {module:model/DeleteWalletRequest}
     */
    DeleteWalletRequest,

    /**
     * The ExportWalletRequest model constructor.
     * @property {module:model/ExportWalletRequest}
     */
    ExportWalletRequest,

    /**
     * The ExportWalletResponse model constructor.
     * @property {module:model/ExportWalletResponse}
     */
    ExportWalletResponse,

    /**
     * The GenerateWalletRequest model constructor.
     * @property {module:model/GenerateWalletRequest}
     */
    GenerateWalletRequest,

    /**
     * The GetAllWalletsResponse model constructor.
     * @property {module:model/GetAllWalletsResponse}
     */
    GetAllWalletsResponse,

    /**
     * The GetBlocksRequest model constructor.
     * @property {module:model/GetBlocksRequest}
     */
    GetBlocksRequest,

    /**
     * The GetBlocksResponse model constructor.
     * @property {module:model/GetBlocksResponse}
     */
    GetBlocksResponse,

    /**
     * The GetNewAddressRequest model constructor.
     * @property {module:model/GetNewAddressRequest}
     */
    GetNewAddressRequest,

    /**
     * The GetNewAddressResponse model constructor.
     * @property {module:model/GetNewAddressResponse}
     */
    GetNewAddressResponse,

    /**
     * The GetPublicKeyRequest model constructor.
     * @property {module:model/GetPublicKeyRequest}
     */
    GetPublicKeyRequest,

    /**
     * The GetPublicKeyResponse model constructor.
     * @property {module:model/GetPublicKeyResponse}
     */
    GetPublicKeyResponse,

    /**
     * The GetRulesResponse model constructor.
     * @property {module:model/GetRulesResponse}
     */
    GetRulesResponse,

    /**
     * The GetTransactionsRequest model constructor.
     * @property {module:model/GetTransactionsRequest}
     */
    GetTransactionsRequest,

    /**
     * The GetTransactionsResponse model constructor.
     * @property {module:model/GetTransactionsResponse}
     */
    GetTransactionsResponse,

    /**
     * The GetWalletBalanceRequest model constructor.
     * @property {module:model/GetWalletBalanceRequest}
     */
    GetWalletBalanceRequest,

    /**
     * The GetWalletBalanceResponse model constructor.
     * @property {module:model/GetWalletBalanceResponse}
     */
    GetWalletBalanceResponse,

    /**
     * The ImportWalletRequest model constructor.
     * @property {module:model/ImportWalletRequest}
     */
    ImportWalletRequest,

    /**
     * The IssueAssetRequest model constructor.
     * @property {module:model/IssueAssetRequest}
     */
    IssueAssetRequest,

    /**
     * The Rule model constructor.
     * @property {module:model/Rule}
     */
    Rule,

    /**
     * The TransactionsForWallet model constructor.
     * @property {module:model/TransactionsForWallet}
     */
    TransactionsForWallet,

    /**
     * The TransferAssetRequest model constructor.
     * @property {module:model/TransferAssetRequest}
     */
    TransferAssetRequest,

    /**
     * The TransferAssetRequestRecipientAddress model constructor.
     * @property {module:model/TransferAssetRequestRecipientAddress}
     */
    TransferAssetRequestRecipientAddress,

    /**
     * The UnlockWalletRequest model constructor.
     * @property {module:model/UnlockWalletRequest}
     */
    UnlockWalletRequest,

    /**
    * The AnalyticsApi service constructor.
    * @property {module:api/AnalyticsApi}
    */
    AnalyticsApi,

    /**
    * The NodeApi service constructor.
    * @property {module:api/NodeApi}
    */
    NodeApi,

    /**
    * The WalletApi service constructor.
    * @property {module:api/WalletApi}
    */
    WalletApi
};
