/*
 * QEDIT - Asset Transfers
 *
 * This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
 *
 * API version: 1.7.2
 * Contact: dev@qed-it.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goqedit
// TaskState : A fine-grained status of the node's inner state. This field is subject to changes and should not be relied upon during development.
type TaskState string

// List of TaskState
const (
	PENDING_STATE TaskState = "pending_state"
	IN_PROGRESS_STATE TaskState = "in_progress_state"
	TX_GENERATED_STATE TaskState = "tx_generated_state"
	CONF_REQ_SENT_STATE TaskState = "conf_req_sent_state"
	CONF_REQ_RECEIVED_STATE TaskState = "conf_req_received_state"
	CONF_REQ_CANCELED_BY_SENDER_STATE TaskState = "conf_req_canceled_by_sender_state"
	CONF_REQ_CANCELED_BY_RECEIVER_STATE TaskState = "conf_req_canceled_by_receiver_state"
	TX_SUBMITTED_STATE TaskState = "tx_submitted_state"
	FAILURE_STATE TaskState = "failure_state"
	SUCCESS_STATE TaskState = "success_state"
)