/*
 * QEDIT - Asset Transfers
 *
 * This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
 *
 * API version: 1.6.2
 * Contact: dev@qed-it.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goqedit
// TaskType : Task type
type TaskType string

// List of TaskType
const (
	TRANSFER_ASSET TaskType = "transfer_asset"
	ISSUE_ASSET TaskType = "issue_asset"
	ALTER_RULE TaskType = "alter_rule"
	IMPORT_WALLET TaskType = "import_wallet"
	DELETE_WALLET TaskType = "delete_wallet"
	OUTGOING_CONFIRM_REQUEST TaskType = "outgoing_confirm_request"
	INCOMING_CONFIRM_REQUEST TaskType = "incoming_confirm_request"
	CANCELLATION TaskType = "cancellation"
)