/*
 * QEDIT - Asset Transfers
 *
 * This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
 *
 * API version: 1.7.0
 * Contact: dev@qed-it.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goqedit

type AnalyticWalletMetadata struct {
	Type AnalyticsTxType `json:"type,omitempty"`
	// The QEDIT-generated hash of the transaction
	TxHash string `json:"tx_hash,omitempty"`
	// UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format
	Timestamp string `json:"timestamp,omitempty"`
}
