/*
 * QEDIT - Asset Transfers
 *
 * This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
 *
 * API version: 1.7.0
 * Contact: dev@qed-it.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package goqedit

type ShareWalletViewingPermissionRequest struct {
	// The ID of the Wallet to export a viewing key for
	WalletId string `json:"wallet_id"`
	// The authorization password for the Wallet
	Authorization string `json:"authorization"`
	// An Address of the Wallet that belongs to the intended recipient of the exported viewing key; used to automatically send the key to the recipient in a secure and private manner
	RecipientPaymentAddress string `json:"recipient_payment_address"`
	// The wallet id assigned by the sender and used to identify the shared wallet on the recipient's Node.
	ShareWalletIdAs string `json:"share_wallet_id_as"`
}
