/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticTransferWalletTx struct {
	// Boolean signifying whether the Assets were transferred to the Wallet in question; false of the Assets were transferred from the Wallet into another
	IsIncoming bool `json:"is_incoming,omitempty"`
	// The public key of the Wallet the Assets were transferred from
	SenderId string `json:"sender_id,omitempty"`
	// The address of the Wallet the Assets were transferred to
	RecipientAddress string `json:"recipient_address,omitempty"`
	// The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
	AssetId string `json:"asset_id,omitempty"`
	// The amount of Assets transferred
	Amount int32 `json:"amount,omitempty"`
	// The private memo attached to the Transfer
	Memo string `json:"memo,omitempty"`
}
