/*
 * QED-it - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type GetNewAddressResponse struct {
	WalletLabel string `json:"wallet_label"`
	RecipientAddress string `json:"recipient_address"`
}
