/*
 * QED-it - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticsConfidentialIssuanceDescription struct {
	InputCv string `json:"input_cv,omitempty"`
	Zkproof string `json:"zkproof,omitempty"`
	Rule AnalyticsRule `json:"rule,omitempty"`
}
