/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type DeleteWalletRequest struct {
	WalletId      string `json:"wallet_id"`
	Authorization string `json:"authorization,omitempty"`
}
