/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

// Describes what Asset Type and amount were issued; null if the Issuance was confidential
type AnalyticsPublicIssuanceDescription struct {
	// The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
	AssetId string `json:"asset_id"`
	// The amount of Assets issued
	Amount int32 `json:"amount"`
}
