/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type ImportWalletRequest struct {
	// The ID under which to import the Wallet; can be different from the ID the Wallet was stored under in the exporting Node
	WalletId string `json:"wallet_id"`
	// The encrypted secret key of the Wallet
	EncryptedSk string `json:"encrypted_sk"`
	// The authorization password used during Wallet generation that allows to decrypt the encrypted secret key
	Authorization string `json:"authorization"`
	// The salt used in the encryption of the secret key
	Salt string `json:"salt"`
}
