/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticsIssueTx struct {
	Outputs   []AnalyticsOutput `json:"outputs,omitempty"`
	PublicKey string            `json:"public_key,omitempty"`
	Signature string            `json:"signature,omitempty"`
}
