/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticsTransferTx struct {
	AssetConverterDescriptions []AnalyticsAssetConverterProofDescription `json:"asset_converter_descriptions,omitempty"`
	Spends                     []AnalyticsSpendDescription               `json:"spends,omitempty"`
	Outputs                    []AnalyticsOutputDescription              `json:"outputs,omitempty"`
	BindingSig                 string                                    `json:"binding_sig,omitempty"`
	SpendAuthSigs              []string                                  `json:"spend_auth_sigs,omitempty"`
}
