/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type GetNetworkActivityRequest struct {
	StartIndex      int32 `json:"start_index"`
	NumberOfResults int32 `json:"number_of_results"`
}
