/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticIssueWalletTx struct {
	// Boolean signifying whether the Assets were issued to the Wallet in question
	IsIncoming bool `json:"is_incoming,omitempty"`
	// Boolean signifying whether the Wallet used to issue the Assets is the Wallet in question
	IssuedBySelf bool `json:"issued_by_self,omitempty"`
	// The public key of the Wallet that was used to issue the Assets
	SenderId string `json:"sender_id,omitempty"`
	// The Address the Assets were issued to
	RecipientAddress string `json:"recipient_address,omitempty"`
	// The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
	AssetId string `json:"asset_id,omitempty"`
	// The amount of Assets issued
	Amount int32 `json:"amount,omitempty"`
	// Boolean signifying whether the Issuance was done confidentially
	IsConfidential bool `json:"is_confidential,omitempty"`
	// The private memo attached to the Issuance
	Memo string `json:"memo,omitempty"`
}
