/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

// Describes what Asset Type and amount were issued; null if the Issuance was confidential
type AnalyticsPublicIssuanceDescription struct {
	// The ID of the Asset Type issued
	AssetId int32 `json:"asset_id"`
	// The amount of Assets issued
	Amount int32 `json:"amount"`
}
