/*
 * QEDIT - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticsAssetConverterProofDescription struct {
	// The commitment to both the Asset Type and amount of the Note
	InputCv string `json:"input_cv,omitempty"`
	// The commitment to the Asset amount
	AmountCv string `json:"amount_cv,omitempty"`
	// The commitment to the ID of the Asset Type
	AssetCv string `json:"asset_cv,omitempty"`
	// The Proof that the commitment contents match
	Zkproof string `json:"zkproof,omitempty"`
}
