/*
 * QED-it - Asset Transfers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type GetPublicKeyResponse struct {
	WalletLabel string `json:"wallet_label"`
	PublicKey string `json:"public_key"`
}
