# coding: utf-8

"""
    QEDIT - Asset Transfers

    This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/).   # noqa: E501

    OpenAPI spec version: 1.6.2
    Contact: dev@qed-it.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AnalyticsTxMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'AnalyticsTxType',
        'tx_hash': 'str',
        'block_height': 'int',
        'block_hash': 'str',
        'timestamp': 'str',
        'index_in_block': 'int'
    }

    attribute_map = {
        'type': 'type',
        'tx_hash': 'tx_hash',
        'block_height': 'block_height',
        'block_hash': 'block_hash',
        'timestamp': 'timestamp',
        'index_in_block': 'index_in_block'
    }

    def __init__(self, type=None, tx_hash=None, block_height=None, block_hash=None, timestamp=None, index_in_block=None):  # noqa: E501
        """AnalyticsTxMetadata - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._tx_hash = None
        self._block_height = None
        self._block_hash = None
        self._timestamp = None
        self._index_in_block = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if tx_hash is not None:
            self.tx_hash = tx_hash
        if block_height is not None:
            self.block_height = block_height
        if block_hash is not None:
            self.block_hash = block_hash
        if timestamp is not None:
            self.timestamp = timestamp
        if index_in_block is not None:
            self.index_in_block = index_in_block

    @property
    def type(self):
        """Gets the type of this AnalyticsTxMetadata.  # noqa: E501


        :return: The type of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: AnalyticsTxType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AnalyticsTxMetadata.


        :param type: The type of this AnalyticsTxMetadata.  # noqa: E501
        :type: AnalyticsTxType
        """

        self._type = type

    @property
    def tx_hash(self):
        """Gets the tx_hash of this AnalyticsTxMetadata.  # noqa: E501

        the QEDIT-generated hash of the transaction  # noqa: E501

        :return: The tx_hash of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: str
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this AnalyticsTxMetadata.

        the QEDIT-generated hash of the transaction  # noqa: E501

        :param tx_hash: The tx_hash of this AnalyticsTxMetadata.  # noqa: E501
        :type: str
        """

        self._tx_hash = tx_hash

    @property
    def block_height(self):
        """Gets the block_height of this AnalyticsTxMetadata.  # noqa: E501

        The height of the Block (inside the Blockchain) that the transaction is a part of  # noqa: E501

        :return: The block_height of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: int
        """
        return self._block_height

    @block_height.setter
    def block_height(self, block_height):
        """Sets the block_height of this AnalyticsTxMetadata.

        The height of the Block (inside the Blockchain) that the transaction is a part of  # noqa: E501

        :param block_height: The block_height of this AnalyticsTxMetadata.  # noqa: E501
        :type: int
        """

        self._block_height = block_height

    @property
    def block_hash(self):
        """Gets the block_hash of this AnalyticsTxMetadata.  # noqa: E501

        the hash of the Block (inside the Blockchain) that the transaction is a part of  # noqa: E501

        :return: The block_hash of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: str
        """
        return self._block_hash

    @block_hash.setter
    def block_hash(self, block_hash):
        """Sets the block_hash of this AnalyticsTxMetadata.

        the hash of the Block (inside the Blockchain) that the transaction is a part of  # noqa: E501

        :param block_hash: The block_hash of this AnalyticsTxMetadata.  # noqa: E501
        :type: str
        """

        self._block_hash = block_hash

    @property
    def timestamp(self):
        """Gets the timestamp of this AnalyticsTxMetadata.  # noqa: E501

        UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format  # noqa: E501

        :return: The timestamp of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this AnalyticsTxMetadata.

        UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format  # noqa: E501

        :param timestamp: The timestamp of this AnalyticsTxMetadata.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def index_in_block(self):
        """Gets the index_in_block of this AnalyticsTxMetadata.  # noqa: E501

        The serial number within the Block of the transaction relative to other QEDIT transactions; indexing is 0-based  # noqa: E501

        :return: The index_in_block of this AnalyticsTxMetadata.  # noqa: E501
        :rtype: int
        """
        return self._index_in_block

    @index_in_block.setter
    def index_in_block(self, index_in_block):
        """Sets the index_in_block of this AnalyticsTxMetadata.

        The serial number within the Block of the transaction relative to other QEDIT transactions; indexing is 0-based  # noqa: E501

        :param index_in_block: The index_in_block of this AnalyticsTxMetadata.  # noqa: E501
        :type: int
        """

        self._index_in_block = index_in_block

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyticsTxMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
