# coding: utf-8

"""
    QEDIT - Asset Transfers

    This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/).   # noqa: E501

    OpenAPI spec version: 1.7.2
    Contact: dev@qed-it.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ExportAuditorAccessWalletResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'wallet_id': 'str',
        'public_key': 'str',
        'access_key': 'str'
    }

    attribute_map = {
        'wallet_id': 'wallet_id',
        'public_key': 'public_key',
        'access_key': 'access_key'
    }

    def __init__(self, wallet_id=None, public_key=None, access_key=None):  # noqa: E501
        """ExportAuditorAccessWalletResponse - a model defined in OpenAPI"""  # noqa: E501

        self._wallet_id = None
        self._public_key = None
        self._access_key = None
        self.discriminator = None

        self.wallet_id = wallet_id
        self.public_key = public_key
        self.access_key = access_key

    @property
    def wallet_id(self):
        """Gets the wallet_id of this ExportAuditorAccessWalletResponse.  # noqa: E501

        The ID of the exported Wallet in the Node from which it was exported  # noqa: E501

        :return: The wallet_id of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :rtype: str
        """
        return self._wallet_id

    @wallet_id.setter
    def wallet_id(self, wallet_id):
        """Sets the wallet_id of this ExportAuditorAccessWalletResponse.

        The ID of the exported Wallet in the Node from which it was exported  # noqa: E501

        :param wallet_id: The wallet_id of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :type: str
        """
        if wallet_id is None:
            raise ValueError("Invalid value for `wallet_id`, must not be `None`")  # noqa: E501

        self._wallet_id = wallet_id

    @property
    def public_key(self):
        """Gets the public_key of this ExportAuditorAccessWalletResponse.  # noqa: E501

        The public key of the exported Wallet which uniquely identifies it across the network  # noqa: E501

        :return: The public_key of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this ExportAuditorAccessWalletResponse.

        The public key of the exported Wallet which uniquely identifies it across the network  # noqa: E501

        :param public_key: The public_key of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :type: str
        """
        if public_key is None:
            raise ValueError("Invalid value for `public_key`, must not be `None`")  # noqa: E501

        self._public_key = public_key

    @property
    def access_key(self):
        """Gets the access_key of this ExportAuditorAccessWalletResponse.  # noqa: E501

        The encrypted viewing key  # noqa: E501

        :return: The access_key of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :rtype: str
        """
        return self._access_key

    @access_key.setter
    def access_key(self, access_key):
        """Sets the access_key of this ExportAuditorAccessWalletResponse.

        The encrypted viewing key  # noqa: E501

        :param access_key: The access_key of this ExportAuditorAccessWalletResponse.  # noqa: E501
        :type: str
        """
        if access_key is None:
            raise ValueError("Invalid value for `access_key`, must not be `None`")  # noqa: E501

        self._access_key = access_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExportAuditorAccessWalletResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
